### ISSUE TITLE
Zoltan help needed:  new version and new repo

### ISSUE THREAD

**Issue by kddevin** [conda-forge/zoltan-feedstock#12]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Zoltan distributions have moved to a new repo at github and a new release is available:
new version 3.90:  https://github.com/sandialabs/Zoltan/releases/tag/v3.90
old version 3.83:  https://github.com/sandialabs/Zoltan/releases/tag/v3.83

Unfortunately, I do not know how to update the recipes to identify these new versions.  @iulian787 and @vijaysm are interested in conda installs of the new version.

Thanks for your help.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by kddevin** [comment]
Actually, I see some updates here from July 9; is this PR acceptable?
https://github.com/conda-forge/zoltan-feedstock/pull/9

@xylar

**Comment by xylar** [comment]
made the PR but the maintainers didn't merge it. So I'm happy to rebase it but don't want to push too hard if it's not of interest...

**Comment by cekees** [comment]
This should be fine for what I use zoltan for. I think #9 needs to be re-rendered again? It's got conflicts...
